### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ZhuLvs** [timkartar/DeepPBS#11]
Hello! The following error occurred on the web version. How can I resolve it?

Log:
Processing co-crystal...

Processing file &#x27;172614849584.tmp.pdb&#x27;
no ATOM/HETATM records found!

Time used: 00:00:00:00
done with cleaning up files.

Time used: 00:00:00:00
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../process_co_crystal.py&quot;, line 72, in &lt;module&gt;
    dna_data = processDNA(dna, quiet=False, prefix=ARGS.timeString)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/process_dna.py&quot;, line 1542, in processDNA
    data = runDSSR(structure, quiet, prefix=prefix)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/process_dna.py&quot;, line 136, in runDSSR
    with open(&quot;{}-dssr.json&quot;.format(prefix)) as FH:
FileNotFoundError: [Errno 2] No such file or directory: &#x27;172614849584-dssr.json&#x27;
rm: cannot remove &#x27;*.par&#x27;: No such file or directory
rm: cannot remove &#x27;*.r3d&#x27;: No such file or directory
rm: cannot remove &#x27;*.dat&#x27;: No such file or directory
Running prediction...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../predict.py&quot;, line 93, in &lt;module&gt;
    dataset, transforms, info, datafiles = loadDataset(datafiles, C[&quot;nc&quot;], C[&quot;labels_key&quot;], C[&quot;data_dir&quot;],
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 261, in loadDataset
    dataset, transforms, data_files = _processData(data_files, nc, labels_key, **kwargs)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 145, in _processData
    data_arrays = np.load(f, allow_pickle=True)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../../../backend/media/uploads/../../../backend/media/uploads/172614849584.npz&#x27;
Calculating heavy atom relative importance (RI) scores...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../interpret.py&quot;, line 90, in &lt;module&gt;
    dataset, transforms, info, datafiles = loadDataset(datafiles, C[&quot;nc&quot;], C[&quot;labels_key&quot;], C[&quot;data_dir&quot;],
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 261, in loadDataset
    dataset, transforms, data_files = _processData(data_files, nc, labels_key, **kwargs)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 145, in _processData
    data_arrays = np.load(f, allow_pickle=True)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../../../backend/media/uploads/172614849584.npz&#x27;
Running Pymol scripts...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 467, in run
    run_(path, ns_pymol, ns_pymol)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 516, in run_file
    execfile(file,global_ns,local_ns)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 511, in execfile
    exec(co, global_ns, local_ns)
  File &quot;../plot_scripts/vis_interpret.py&quot;, line 25, in &lt;module&gt;
    v_prot_all = np.load(npy_path + &quot;_v_prot.npy&quot;) # coords all protein atoms
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../plot_scripts//interpret_output/172614849584.npz_v_prot.npy&#x27;
 Error: unsupported file type: 
 Error: Argument processing aborted due to exception (above).
mv: cannot stat &#x27;../plot_scripts/interpret_output/172614849584.*&#x27;: No such file or directory
mv: cannot stat &#x27;../../../backend/media/output/npzs/172614849584.npz_predict.npz&#x27;: No such file or directory
mv: cannot stat &#x27;../../../backend/media/uploads/172614849584.npz&#x27;: No such file or directory

**Comment by ZhuLvs** [comment]
new error

Log:
Processing co-crystal...

Processing file &#x27;172615067833.tmp.pdb&#x27;
    total number of nucleotides: 23
    total number of base pairs: 11
    total number of multiplets: 3
    total number of helices: 1
    total number of non-pairing interactions: 19
    total number of atom-base capping interactions: 3
    total number of splayed-apart dinucleotides: 9
                        consolidated into units: 5

boundary for lvector(): [1 to 0]
    total number of G-tetrads: 1
    total number of non-loop single-stranded segments: 1

Time used: 00:00:00:00
done with cleaning up files.

Time used: 00:00:00:00
ERROR: helix count problem 0 172615067833.pdb
rm: cannot remove &#x27;*.par&#x27;: No such file or directory
rm: cannot remove &#x27;*.r3d&#x27;: No such file or directory
rm: cannot remove &#x27;*.dat&#x27;: No such file or directory
Running prediction...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../predict.py&quot;, line 93, in &lt;module&gt;
    dataset, transforms, info, datafiles = loadDataset(datafiles, C[&quot;nc&quot;], C[&quot;labels_key&quot;], C[&quot;data_dir&quot;],
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 261, in loadDataset
    dataset, transforms, data_files = _processData(data_files, nc, labels_key, **kwargs)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 145, in _processData
    data_arrays = np.load(f, allow_pickle=True)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../../../backend/media/uploads/../../../backend/media/uploads/172615067833.npz&#x27;
Calculating heavy atom relative importance (RI) scores...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../interpret.py&quot;, line 90, in &lt;module&gt;
    dataset, transforms, info, datafiles = loadDataset(datafiles, C[&quot;nc&quot;], C[&quot;labels_key&quot;], C[&quot;data_dir&quot;],
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 261, in loadDataset
    dataset, transforms, data_files = _processData(data_files, nc, labels_key, **kwargs)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 145, in _processData
    data_arrays = np.load(f, allow_pickle=True)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../../../backend/media/uploads/172615067833.npz&#x27;
Running Pymol scripts...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 467, in run
    run_(path, ns_pymol, ns_pymol)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 516, in run_file
    execfile(file,global_ns,local_ns)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/pymol/parsing.py&quot;, line 511, in execfile
    exec(co, global_ns, local_ns)
  File &quot;../plot_scripts/vis_interpret.py&quot;, line 25, in &lt;module&gt;
    v_prot_all = np.load(npy_path + &quot;_v_prot.npy&quot;) # coords all protein atoms
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../plot_scripts//interpret_output/172615067833.npz_v_prot.npy&#x27;
 Error: unsupported file type: 
 Error: Argument processing aborted due to exception (above).
mv: cannot stat &#x27;../plot_scripts/interpret_output/172615067833.*&#x27;: No such file or directory
mv: cannot stat &#x27;../../../backend/media/output/npzs/172615067833.npz_predict.npz&#x27;: No such file or directory
mv: cannot stat &#x27;../../../backend/media/uploads/172615067833.npz&#x27;: No such file or directory

**Comment by timkartar** [comment]
Try removing the ".tmp" part from the file name and make sure there is exactly one DNA helix in there.

**Comment by ZhuLvs** [comment]
Hello! Thank you for your response!

My input result is the docking result from HADDOCK, and indeed, there is only one DNA. I would greatly appreciate it if you could take a look! Thank you very much!
https://deeppbs.usc.edu/link/172628569750

**Comment by timkartar** [comment]
Ok, I looked at the uploaded file.

As you can see the error message says "ERROR: missing C5/OP1/OP1/OP2".

This is because the HADDOCK output PDB file names phosphate oxygen atoms as "O1P/O2P" instead of "OP1/OP2". Try renaming these atoms to "OP1/OP2". Hopefully that works. 

The helix score of 0.166.. is really low though for the structure. But hopefully it works!

**Comment by ZhuLvs** [comment]
Thank you very much for your help!
