### ISSUE TITLE
Input loading error

### ISSUE THREAD

**Issue by miminuska** [timkartar/DeepPBS#13]
Hello! 
I would like to use your web server version of DeepPBS. For my porject I would like to analyse telomere binding proteins as they may bind several DNA sequences, for me it would be very interesting to see these sequences as the PWM.

At first, I wanted to test out several protein-DNA structures, however, in all cases my input was not "accepted" and an error message popped out:

"Error loading file! This is most commonly caused by a structure file that is too large or formatted improperly."

I received this message even with the 8OJ1 structure that is set as an example in FAQ section and 3Q05 mentioned in the paper. I used .cif format, downloaded from the rcsb.org.

Is there anything I could do with that?

Thank you in advance :)

**Comment by timkartar** [comment]
Hi there, I just ran 8oj1, on the webserver and it worked OK for me. See output here: https://deeppbs.usc.edu/link/172655509484 

I think the issue you are facing is some form of network security/firewall issue, which is preventing the upload from happening. If you want to me try further, You can share a structure file (even the 8oj1 one) that failed for you. And I can try to run that file and see if I get the same error.

Thanks !

**Comment by miminuska** [comment]
Thank you for your help. Looks like the change of the web browser was the problem...the 3Q05 ran in Google Chrome without any issues and resulted without any problem. On the other hand the 8oj1.cif ended up with another error. The web page loaded this message:

```
Log:
Processing co-crystal...

Processing file &#x27;17265557210.tmp.pdb&#x27;
    total number of nucleotides: 21
    total number of non-pairing interactions: 19

boundary for lvector(): [1 to 0]
    total number of non-loop single-stranded segments: 1

Time used: 00:00:00:00
done with cleaning up files.

Time used: 00:00:00:00
ERROR: helix count problem 0 17265557210.cif
rm: cannot remove &#x27;*.par&#x27;: No such file or directory
rm: cannot remove &#x27;*.r3d&#x27;: No such file or directory
rm: cannot remove &#x27;*.dat&#x27;: No such file or directory
Running prediction...
Traceback (most recent call last):
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/run/process/../predict.py&quot;, line 93, in &lt;module&gt;
    dataset, transforms, info, datafiles = loadDataset(datafiles, C[&quot;nc&quot;], C[&quot;labels_key&quot;], C[&quot;data_dir&quot;],
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 261, in loadDataset
    dataset, transforms, data_files = _processData(data_files, nc, labels_key, **kwargs)
  File &quot;/srv/www/deeppbs.usc.edu/deeppbs-webserver/deeppbs/deeppbs/nn/utils/load_data.py&quot;, line 145, in _processData
    data_arrays = np.load(f, allow_pickle=True)
  File &quot;/srv/www/deeppbs.usc.edu/conda/lib/python3.9/site-packages/numpy/lib/npyio.py&quot;, line 427, in load
    fid = stack.enter_context(open(os_fspath(file), &quot;rb&quot;))
FileNotFoundError: [Errno 2] No such file or directory: &#x27;../../../backend/media/uploads/../../../backend/media/uploads/17265557210.npz&#x27;
mv: cannot stat &#x27;../../../backend/media/output/npzs/17265557210.npz_predict.npz&#x27;: No such file or directory
mv: cannot stat &#x27;../../../backend/media/uploads/17265557210.npz&#x27;: No such file or directory

```
I attach zip file of the structure 8oj1 used as input in this run.
[8oj1.cif.zip](https://github.com/user-attachments/files/17026452/8oj1.cif.zip)

Thank you so much for your time and patience.

**Comment by timkartar** [comment]
I think this is happening because you are using the assymetric unit(which has ssDNA) file for 8oj1 instead of the biological assembly (which has an helix). Please use the biological asembly file. The webserver mentions this in FAQ.

**Comment by miminuska** [comment]
Thank you!
