### ISSUE TITLE
special DNA pdb cannot process

### ISSUE THREAD

**Issue by yz103** [timkartar/DeepPBS#15]
For the pdb 7f75.pdb , since it is a promoter binding with RNA polymerase to start transcription, and partial of DNA is unpair which looks like the following picture,
![image](https://github.com/user-attachments/assets/67c83d49-0a51-4c51-91d2-8d72c75652ac)
processing this file will generate "error: helix count problem" and i guess it consider it as 2 dna pairs but which actually just one dna pairs and partial of it is depaired for transcription. Is there a solution to solve this? Thank you very much for  your help.

**Comment by timkartar** [comment]
Thanks for the question. You can delete the small helical region at the top left of the picture you shared. Then it should detect only one helix and it should work (instead of detecting 2, which is the reason for the error currently)

**Comment by yz103** [comment]
Thank you very much for the reply. I havent read the code very carefully but from the papers it seems like it only used the DNA features from the paired part right? So it would not predict the unpaired part motif , am I right?

**Comment by timkartar** [comment]
Yes. It will predict on the helical region only !

**Comment by yz103** [comment]
Thank you very much for your response
