### ISSUE TITLE
Is input Protein-DNA model quality important for RI calculation?

### ISSUE THREAD

**Issue by XuXinwaxx** [timkartar/DeepPBS#2]
Hi,

I'm currently working on a protein that binds to a specific 18bp DNA sequence, supported by experimental evidence, and I'm trying to identify the conserved binding motif. However, the challenge I'm facing is the lack of structural data. I tried predicting the structure using RosettaFold-AA and AlphaFold3, but the results show the DNA and protein are not close to each other, suggesting that the models do not predict a significant binding or interaction.

Given this situation, I'm wondering whether using DEEPBS with such predicted structures could still generate reliable motif results. I would appreciate any insights or advice on this.

Thanks a lot!

**Comment by timkartar** [comment]
Hi there,

If the structure prediction model fails to model a complex properly i.e. in your case, doesn't put the DNA near the protein, i do not recommend using such a prediction. In this case, DeepPBS will only predict the motif based on the DNA shape in the predicted complex, the protien will not be considered. However, there are other ways you could model a complex like HADDOCK (or MELD-DNA). These will probably do a better job than AF3/RF-AA (in terms of docking the protein to the DNA) . 

In addition, if you are only specifically interested in this system, you can also run an MD of the HADDOCK docked complex and pick out a few different representative conformations and try all of them.

Hope this is helpful.

**Comment by timkartar** [comment]
Closing this as resolved. Feel free to reopen for further discussion.
