### ISSUE TITLE
Relative Importance (RI) Score for Binding Affinity Calculation

### ISSUE THREAD

**Issue by ChangShaole** [timkartar/DeepPBS#5]
Hi, DeepPBS Team

Thanks for sharing such a great framework!
I noticed in the paper a 0.6 PCC between the log sum of the RI score and the exp \delta\delta G. It's quite a good value.
Recently I wanted to find a tool for calculating the protein-DNA affinity for my system. So I noticed this paper. However, when I ran the DeepPBS for the protein-DNA structures, I didn't find the RI score in the output files.

Please tell me where I can find the scores. :)

**Comment by timkartar** [comment]
Hi ! The RI scores are produced in the form of a few different files (xxx.npz_diffs.npy, xxx.npz_edge_index.py, xxx.npz_v_prot.npy, xxx.npz_xprot.npy). See upto line 34 in https://github.com/timkartar/DeepPBS/blob/main/run/plot_scripts/vis_interpret.py to see how these files are used to get the normalized `diffs` (which is the RI score for each vertex  in `v_prot` (line 29)). 

You will need to match your atom coordinates with the coordinates  in `v_prot` to create a correspondance. 

Please note that we did not compute \delta G from these (i.e. the full binding affinity of your system). The correlation shown is only with mutagenesis  \delta\delta G of single residues in the protein-DNA interface.

Let me know if this is helpful.

**Comment by ChangShaole** [comment]
Thanks for this quick reply! :)
I will try to process the .npy data following you later. But there is a thing I want to find out first.
As you said, the relationship is between the RI score and the \delta\delta G. What I need to do is a little bit like virtual screening, the interface will be changed more than the single res mutagenesis. So I am just wondering if I can use DeepPBS for this task. Anyway, It will also be helpful for my later task!
Do you have any idea :)

**Comment by ChangShaole** [comment]
For more info on the virtual screening task, the target is a set of DNAs.

**Comment by timkartar** [comment]
Sounds like it's definitely worth a try !

**Comment by timkartar** [comment]
Closing this for now. Please feel free to reopen if you have further questions.
