### ISSUE TITLE
protein-DNA

### ISSUE THREAD

**Issue by ZhuLvs** [timkartar/DeepPBS#6]
Dear Author,

I am currently working on a project related to protein-DNA interactions. However, my data consists of separate PDB files for the protein and DNA, rather than their complex. Would it be feasible to simply combine them into a complex using PyMOL and then use this complex as input for DeepPBS?

**Comment by timkartar** [comment]
Hi ! I am not sure I fully understand your question. You can use Biopython to programmatically combine two pdb files into a new one. But if you mean you are trying to dock them, then I suggest trying something like HADDOCK.

Hope this is helpful.

**Comment by ZhuLvs** [comment]
Hello! I am attempting to design proteins from scratch that can interact with specific DNA. Currently, I have separate PDB files for the protein and the DNA. I want to use DeepPBS to perform a pre-experimental screening. However, I noticed that DeepPBS requires the input to be a protein-DNA complex. So, do I need to provide a docked complex, or is it sufficient to simply write the protein and DNA into a single PDB file?

**Comment by timkartar** [comment]
You will need to provide a docked complex. Similar to the complexes designed by Glasscock et. al. ( https://www.biorxiv.org/content/10.1101/2023.09.20.558720v1 ), few of which we use in our paper's figure 5.

**Comment by timkartar** [comment]
I am closing this now as this is not an implementation/code issue. Please feel free to reopen if you have further questions !

**Comment by ZhuLvs** [comment]
hank you for your recommendation!
Is it feasible to directly combine the protein monomer PDB with DNA using PyMOL or Biopython and then use it as input for DeepPBS?

**Comment by ZhuLvs** [comment]
Thank you for your recommendation!
Is it feasible to directly combine the protein monomer PDB with DNA using PyMOL or Biopython and then use it as input for DeepPBS to predict their interactions?

**Comment by timkartar** [comment]
Hi there, I don't think PyMOL or Biopython can do protein-DNA docking. I recommend you checkout docking tools like HADDOCK, MELD-DNA or prediction tools like AlphaFold3/RoseTTAFoldNA.

**Comment by ZhuLvs** [comment]
Thank you very much for your help!
