### ISSUE TITLE
Your job was unable to process correctly. Please ensure the file you uploaded was valid

### ISSUE THREAD

**Issue by Somanath-SS** [timkartar/DeepPBS#7]
FIles are valid,
The only issue is,
If the file is containing more than one DNA molecules, DeepPBS isnt able to process it.

**Comment by timkartar** [comment]
You have to create separate files with one DNA helix in each. You can achieve this using pyMOL or Biopython. Hope this is helpful.

**Comment by Somanath-SS** [comment]
so DeepPBS can uptake one Dna molecule(limited length) at a time, but irrespective of the number of protein?

**Comment by timkartar** [comment]
Yes (except no limit on DNA length). Please read the FAQ page on the webserver for basic requirements. 
deeppbs.usc.edu/ -> 'show FAQ'

Closing this now. Please feel free to reopen with a more specific query (e.g. example of a file that u r trying to run and if anything unique is happening there that is not covered in the FAQ)
